### PR TITLE
TouK's Check.id

### PR DESCRIPTION
**Pull request by pivovarit**

### CODE REVIEW

**Comment by danieldietrich** [comment]
Hi @pivovarit, thanks - great to hear you use Javaslang! Do you have an example what you use Javaslang for? You have ThrowingFunctions and better java monads (Try) and I can't find any Javaslang in the TouK github organization.
Thx
Daniel

**Comment by pivovarit** [comment]
Hi @danieldietrich !
Well, we are using Javaslang in our commercial projects on daily basis, but unfortunately we can't really speak publically about them and neither show some code. Check.id is our own commercial project and we can whatever we want with it, but we are definitely not going open-source with this one

**Comment by pivovarit** [comment]
Or were you asking about specific Javaslang applications in our code?
PatternMatching and FailureHandling with Try monad are the things we use most

**Comment by danieldietrich** [comment]
Thanks, Check.id looks nice!

The next major version of Javaslang will have a re-work of match. I will take care of giving a good migration path. We could ship the old match API and deprecate it but I think it is worth to adapt the new syntax. However, it isn't fully available yet.

**Pull request merged**
